### ISSUE TITLE
error while producing the *_SJ.out.tab file

### ISSUE THREAD

**Issue by chklopp** [sagnikbanerjee15/Finder#11]
Hi,

I encountered the following error during the alignment step while finder was outputting the *_SJ.out.tab file

cat Finder.output
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Finder/finder-113203c/finder", line 640, in <module>
    main()
  File "/usr/local/bioinfo/src/Finder/finder-113203c/finder", line 601, in main
    orchestrateGeneModelPrediction(options,logger_proxy,logging_mutex)
  File "/usr/local/bioinfo/src/Finder/finder-113203c/finder", line 385, in orchestrateGeneModelPrediction
    alignReadsAndMergeOutput(options,logger_proxy,logging_mutex)
  File "/usr/local/bioinfo/src/Finder/finder-113203c/scripts/findGenesFromExpression.py", line 313, in alignReadsAndMergeOutput
    selectHighConfidenceSpliceJunctions(options,1,condition)
  File "/usr/local/bioinfo/src/Finder/finder-113203c/scripts/findGenesFromExpression.py", line 105, in selectHighConfidenceSpliceJunctions
    condition,junctions_to_be_discarded,junctions_to_be_retained=selectHighConfidenceSpliceJunctionsPerCondition([condition,options,round])
  File "/usr/local/bioinfo/src/Finder/finder-113203c/scripts/findGenesFromExpression.py", line 46, in selectHighConfidenceSpliceJunctionsPerCondition
    chromosome,j_start,j_end,strand,intron_motif,annotated,uniq_reads,mm_reads,max_overhang=line.strip().split()
ValueError: not enough values to unpack (expected 9, got 8)

What should I do?

**Comment by sagnikbanerjee15** [comment]
Hello @chklopp,

Thank you for reporting this issue. Could you please attach the metadata file and the `*_SJ.out.tab` files? Please attach all the `*_SJ.out.tab` files. It will help to figure out the problem faster.

Thank you.

**Comment by chklopp** [comment]
metadata.tsv file
http://genoweb.toulouse.inra.fr/~klopp/Finder/metadata.tsv

*_SJ.out.tab file
http://genoweb.toulouse.inra.fr/~klopp/Finder/SRR1025320_round1_SJ.out.tab

**Comment by sagnikbanerjee15** [comment]
Hello @chklopp,

I ran the entire program from my end but it did not produce the error you reported. Could you please remove the output directory and run it again?

Thank you.

**Comment by chklopp** [comment]
This did not work.
Do you know the command line run to generate *_SJ.out.tab from *_Aligned.sortedByCoord.out.bam ?
I would like to check if there is something wrong in my bam file.

**Comment by sagnikbanerjee15** [comment]
Hello @chklopp,

Thank you for checking it out. It is STAR that generated the *SJ.out.tab files during the alignment step. FINDER reads in that information and attempts to understand if the splice junctions are valid and also seen in other RNASeq samples. Could you please tell me the genome which you are annotating? During my test run I downloaded it from ensembl. I did notice that there was one line in the SJ.out.tab file which did not have 9 columns. Could you please send me the Log.out file for the RNASeq sample alignment? Also which version of STAR are you using? I will try to solve this from my end but I might have to get in touch with the developers of STAR to sort this out.

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello @chklopp,

Thank you for sending me the log file. I see that the execution has completed without any obvious error. I will post on STAR's github to see if they can help us out.

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hi @chklopp,

I think you have checked out Ales's reply about the issue you are facing. Will it be possible for you to run `finder` on a different system?

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hi @chklopp,

Could you please send me over all your data? I can run those on my end and email you the results. Please send the genome, RNA-Seq samples, and the protein file (if you are using any) to sagnik@iastate.edu.

Thank you.
