### ISSUE TITLE
'Another job is still loading the genome, sleeping for 1 min'

### ISSUE THREAD

**Issue by peterdfields** [sagnikbanerjee15/Finder#14]
Hi @sagnikbanerjee15 

I am trying to run Finder on a fairly fragmented genome of around 500Mbp. Running the example dataset was successful. When I try running my own dataset of a single RNAseq dataset the program seems to get stuck very early on while running STAR. Specifically, the `*_round1_Log.out` file has at the bottom repeated instances of `Another job is still loading the genome, sleeping for 1 min`. I can run STAR on the dataset independent of finder so I'm wondering if you have an idea about what might be going wrong here? Thank you for your time and advice.

**Comment by sagnikbanerjee15** [comment]
Hello @peterdfields,

Thank you so much for checking out `finder` and I am glad that the run with the example dataset got over without any issues. I googled the problem you mention here and I think it is because a copy of the genome is still existing in the memory which is not removed before a new run is scheduled. Anyways, I have modified the code slightly. `finder` will remove any existing copies from the RAM before starting a new mapping task. Thank you for reporting this issue. Users like you are the reason why we developers can build better and robust software. Let me know if you run into any issues.

Thank you.

**Comment by peterdfields** [comment]
Hii @sagnikbanerjee15 

Thank you for your response. I pulled the modified finder script and the particular error mentioned in the title is no longer present. However, there might be a related downstream error but I'm not sure. You can have a look at the generated error file at the following gist: https://gist.github.com/peterdfields/502fd3861205d04cee746f66897ec681 Please let me know if any additional information would be helpful. Thank you again for your help and advice.

**Comment by sagnikbanerjee15** [comment]
Hi @peterdfields,

I am glad that the previous issue got sorted out. I checked the error file you posted, and it seems that there is a problem with the genome sequence (line 18). Could you please attach the command you are running the program with. If possible, could you send me the data along with the genome? I would like to run it on my end to troubleshoot the problems. If the data has not yet been released, then you can email me at sagnikbanerjee15@gmail.com.

Thank you.

**Comment by peterdfields** [comment]
Hi @sagnikbanerjee15,

These data are not public yet. It's not a problem to share the reference with you, I can send you a download link. For the reads I'm less sure because the file sizes are quite large. As for the command it's essentially what's described in the example dataset:
```
finder -no_cleanup -mf Pk_rnaseq.csv -n 16 -gdir_star star_index_without_transcriptome -out_dir FINDER_Pk -g P_scaffold_gapfilled_21042021.fasta -p proteins.fasta -gdir_olego olego_index -preserve 1> FINDER_Pk.output 2> FINDER_Pk.error
```
Let me know if I can provide any additional information.

**Comment by sagnikbanerjee15** [comment]
Hello @peterdfields,

Thank you for responding. Please do share the genome, protein sequences and all the RNA-Seq sample reads. Will you be able to gzip the reads? Usually, that can help with the size to some extent. The command to run `finder` looks good to me. 

Thank you.
