### ISSUE TITLE
Issues with transcript_to_condition 

### ISSUE THREAD

**Issue by priyanka8590** [sagnikbanerjee15/Finder#2]
Hello,
Thank you for addressing the issues on finder. I am running finder on Arabidopsis and the execution completes without an error. But when I checked the final GTF files, I found that the file transcript_to_condition does not have quite what I expected. Could you please look into it? Here are the contents of the file.
```
exons	flower,leaf,cold
introns	flower,leaf,cold
cds	flower,leaf,cold
cds_frame	flower,leaf,cold
direction	flower,leaf,cold
TPM	flower,leaf,cold
cov	flower,leaf,cold
gene_id	flower,leaf,cold
FPKM	flower,leaf,cold
transcript_start	flower,leaf,cold
transcript_end	flower,leaf,cold
chromosome	flower,leaf,cold
annotator	flower,leaf,cold
```
```
Thank you.

**Comment by sagnikbanerjee15** [comment]
Hi @priyanka8590,

Thank you for bringing this issue to my attention. I tried it out and indeed `finder` is producing some weird output. I will fix the issue and let you know when it up for you to give it a try.

Thank you.

**Comment by sagnikbanerjee15** [comment]
I have fixed the issue. Please give it a try and let me know if you run into any problems.

Thanks.
