### ISSUE TITLE
Trouble with running the example, maybe from alignReads.py Round4 missing

### ISSUE THREAD

**Issue by LuLiangL** [sagnikbanerjee15/Finder#31]
When I running example data, I follow all pipeline in README.md. But I got a error:

```
Traceback (most recent call last):
  File "/home/software/finder/finder", line 675, in <module>
    main()
  File "/home/software/finder/finder", line 636, in main
    orchestrateGeneModelPrediction(options,logger_proxy,logging_mutex)
  File "/home/software/finder/finder", line 420, in orchestrateGeneModelPrediction
    alignReadsAndMergeOutput(options,logger_proxy,logging_mutex)
  File "/home/software/finder/scripts/findGenesFromExpression.py", line 419, in alignReadsAndMergeOutput
    fhr=open(options.output_star+"/"+Run+"_round4_Log.final.out","r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/software/finder/example/FINDER_test_ARATH/alignments/SRR9844295_round4_Log.final.out'
```

Then I check scripts, I find in findGenesFromExpression.py line 392~412, you've blocked out the code, this part annotation is "Align reads with STAR round4" . But after that, in line 418, The "Align reads with OLego round5" still use round4 result.

Then I check the function "alignReadsWithSTARRound4" in alignReads.py, But I can't find any same name function in alignReads.py.

So this is a bug in Finder? Or can I use round3 result in OLego round5?

**Comment by sagnikbanerjee15** [comment]
Hello @saxovocal and @LuLiangL,

I have made some changes. Could you please run it again and report if the error still persists?

Thank you.

**Comment by saxovocal** [comment]
Hi @sagnikbanerjee15 

the script now stops at:
2021-11-11 17:12:32,661 - finder -   INFO - Information collection about alignments completed 
2021-11-11 17:12:33,554 - finder -   INFO - Generation of assemblies with PsiCLASS completed 

With the following errors: 
`FileNotFoundError: [Errno 2] No such file or directory: '/$/Finder_rerun/assemblies_psiclass_modified/combined/combined.gtf' `

**Comment by sagnikbanerjee15** [comment]
Hi @saxovocal,

Thank you so much for reporting this. It seems like either `psiclass` have encountered a segmentation fault or else the output files were not generated properly. Could you please check if there are core* files in your working directory? If not, then please send me the compressed output folder at sagnikbanerjee15@gmail.com. I need to take a deeper look.

Thank you.

**Comment by saxovocal** [comment]
Hi @sagnikbanerjee15,

I wanted to email you the compressed output folder but it's 78.8 GB **after** compression, so perhaps that's not completely feasible. 

I don't exactly find any core dump files in the directory. Could you possibly give me some other instructions that I can look out for? thanks. 

For your information, I'm running it with 7 bulk rna datasets from the same tissue.

Thanks

**Comment by sagnikbanerjee15** [comment]
Hi @saxovocal,

Thank you for writing back to us. Yes, the file is huge probably because of the several alignment bam files. Could you please share your genome, proteome and the metadata.csv file? I can run it on my end and troubleshoot. Please send those files to sagnikbanerjee15@gmail.com

Thanks.

**Comment by saxovocal** [comment]
@sagnikbanerjee15 I think I've found the problems. 

In the Error file it says:
```
$/Software/finder/dep/psiclass_terminal_exon_length_modified//junc: not found
$/Software/finder/dep/psiclass_terminal_exon_length_modified//subexon-info: not found
```
which probably corresponds to this part i nte script?
```
    options.softwares["junc"]=dep_path+"/psiclass_terminal_exon_length_modified//junc"
    options.softwares["subexon-info"]=dep_path+"/psiclass_terminal_exon_length_modified//subexon-info"
```
I do notice in the PsiClass directory `SubexonInfo.cpp` exists but nothing called `junc`

Would that be the reason? Thanks for your help anyways.

**Comment by sagnikbanerjee15** [comment]
Hi @saxovocal,

Thank you for reporting this. It seems like the installation did not work properly. Could you please reinstall `finder`?

Thanks.
