### ISSUE TITLE
Several bug I found

### ISSUE THREAD

**Issue by ZuyaoLiu** [sagnikbanerjee15/Finder#34]
Hi @sagnikbanerjee15 

I found three bug when using Finder.

1.  In fixOverlappingAndMergedTranscripts.pym line 347, please add "dtype=object" in np.array(temp). Otherwise , there's an annoying warning message.
2. in alignReads.py, line 432, there should be an extra space before "2>". Otherwise, bam2 file would be created, which causes error in the following step.
3. Please update the PsiCLASS to the latest version. There might be problem with genes that have long intron.

Good luck.

Zuyao

**Comment by sagnikbanerjee15** [comment]
Thank you so much @ZuyaoLiu for reporting this. I have made the necessary corrections.

Thank you.
