### ISSUE TITLE
Unable to load modules

### ISSUE THREAD

**Issue by skyungyong** [sagnikbanerjee15/Finder#40]
Hi!

I am having issues with loading modules. Am I missing something in installation?

```
conda activate finder_conda_env
export PATH=$PATH:/global/scratch/users/skyungyong/Software/finder
```

`whereis finder`
finder: /global/scratch/users/skyungyong/Software/finder/finder
`which finder`
/global/scratch/users/skyungyong/Software/finder/finder
`tail -n 1 ~/.bashrc`
export PATH=$PATH:/global/scratch/users/skyungyong/Software/finder

`finder -h`
Traceback (most recent call last):
  File "/global/scratch/users/skyungyong/Software/finder/finder", line 54, in <module>
    from scripts.alignReads import *
ModuleNotFoundError: No module named 'scripts.alignReads'

**Comment by skyungyong** [comment]
Seems to be working after adding __init.py in the scripts folder :)

**Comment by sagnikbanerjee15** [comment]
Hello @skyungyong,

Thank you so much for your interest in `finder`. Please give me about a week. I am currently working on releasing a docker. But it will be a bit different that the original pipeline since some of the dependent software are not redistributable.

Thank you.
