### ISSUE TITLE
Psiclass fault

### ISSUE THREAD

**Issue by vruggieri** [sagnikbanerjee15/Finder#48]
Hi,
Thanks for the nice pipeline. I would very much like to try and use it in my next project. 
However, I am experiencing a Psiclass fault while trying to run Finder with example data (I'm just using 3 RNA-Seq datasets SRR5197915, SRR8422201, SRR8422202). 

**This is the line that cause the fault:**
/softwares/Psiclass/PsiCLASS/classes  -p 20 --primaryParalog  --lb /home/server2/Programs/Finder-finder_v1.1.0/FINDER_test_ARATH/assemblies_psiclass_modified/fofn  -s /home/server2/Programs/Finder-finder_v1.1.0/FINDER_test_ARATH/assemblies_psiclass_modified/combined/subexon/psiclass_output_subexon_combined.out -o /home/server2/Programs/Finder-finder_v1.1.0/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output > /home/server2/Programs/Finder-finder_v1.1.0/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_classes.log

**This the last 20 rows of "psiclass_output_classes.log":**
Thread 5: 3 20666991 20668480 finished.
30914: 2 3 20673832 20675907. Free threads: 14/20
20671127: atCnt=1 seCnt=2 0 3 2
Thread 11: 3 20671127 20672435 finished.
30915: 2 3 20681913 20684035. Free threads: 14/20
20673832: atCnt=1 seCnt=2 0 3 6
Thread 11: 3 20673832 20675907 finished.
30916: 7 3 20695497 20698221. Free threads: 14/20
20681913: atCnt=1 seCnt=2 0 3 5
Thread 11: 3 20681913 20684035 finished.
30917: 5 3 20698535 20700159. Free threads: 14/20
20695497: atCnt=1 seCnt=7 0 11 28
Thread 11: 3 20695497 20698221 finished.
Thread 12: 3 20636589 20639491 finished.
20698535: atCnt=2 seCnt=5 0 9 36
30918: 9 3 20700379 20703042. Free threads: 15/20
Thread 12: 3 20698535 20700159 finished.
20700379: atCnt=6 seCnt=9 0 20 57
30919: 13 3 20703262 20705327. Free threads: 15/20
Thread 12: 3 20700379 20703042 finished.

**Here's the last 10 rows of the Progress file:**
2022-03-03 07:33:21,976 - finder -   INFO - STAR Round3 run for SRR8422202 completed
2022-03-03 07:33:21,977 - finder -   INFO - Mapping of reads for round3 completed for cold
2022-03-03 07:33:21,989 - finder -   INFO - Selecting high confidence junctions after round3 mapping completed for cold
2022-03-03 07:35:18,956 - finder -   INFO - OLego run for SRR8422201 completed
2022-03-03 07:36:47,446 - finder -   INFO - OLego run for SRR8422202 completed
2022-03-03 07:36:47,447 - finder -   INFO - Mapping with OLego for micro-exon detection completed for cold
2022-03-03 07:38:54,777 - finder -   INFO - Merging of alignments from all rounds of mapping completed for cold
2022-03-03 07:38:54,778 - finder -   INFO - Mapping of all runs completed for cold
2022-03-03 08:06:50,383 - finder -   INFO - Information collection about alignments completed 
2022-03-03 08:19:27,161 - finder -   INFO - Generation of assemblies with PsiCLASS completed
 

It seems that programs crash due to memory issue (in resources monitor I saw RAM going up during this step til the limit and then stop). 
I'm using a 20cpus, 64Gb RAM computer.
I've seen you posted a similar problem in psiclass github page issues (https://github.com/splicebox/PsiCLASS/issues/21)

The pipelines (1.1.0) was installed following instruction and it runs using docker (version 20.10.12, build e91ed57).
**This the full command used:**
/usr/bin/time --verbose ./run_finder -no_cleanup -mf $PWD/example/Arabidopsis_thaliana_metadata_local.csv -n 20 -out_dir $PWD/FINDER_test_ARATH -g $PWD/example/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa -p $PWD/example/uniprot_ARATH.fasta -preserve --organism_model PLANTS --genemark_path ~/Programs/gmes_linux_64/ -gml ~/Programs/Finder-finder_v1.1.0/gm_key_64

**This is the stderr:**
1.1.0: Pulling from sagnikbanerjee15/finder
Digest: sha256:9816d258d2421d4625983c929f508b1f577cfe7ab3bc2042e841647a186c7931
Status: Image is up to date for sagnikbanerjee15/finder:1.1.0
docker.io/sagnikbanerjee15/finder:1.1.0
done
mv: cannot stat '/home/server2/Programs/Finder-finder_v1.1.0/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_vote.gtf': No such file or directory
Traceback (most recent call last):
  File "/softwares/FINDER/Finder/finder", line 688, in <module>
    main()
  File "/softwares/FINDER/Finder/finder", line 649, in main
    orchestrateGeneModelPrediction( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/finder", line 461, in orchestrateGeneModelPrediction
    findTranscriptsInEachSampleNotReportedInCombinedAnnotations( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/scripts/findTranscriptsInEachSampleNotReportedInCombinedAnnotations.py", line 17, in findTranscriptsInEachSampleNotReportedInCombinedAnnotations
    combined_transcript_info = readAllTranscriptsFromGTFFileInParallel( [combined_gtf_filename, "combined", "combined"] )[0]
  File "/softwares/FINDER/Finder/scripts/fileReadWriteOperations.py", line 290, in readAllTranscriptsFromGTFFileInParallel
    fhr = open( gtf_filename, "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/home/server2/Programs/Finder-finder_v1.1.0/FINDER_test_ARATH/assemblies_psiclass_modified/combined/combined.gtf'

Do you have any suggestion to solve the issue?
Thank you in advance

**Comment by sagnikbanerjee15** [comment]
Hello @vruggieri,

Thank you so much for your interest in `finder`. I will look into this problem and let you know. The example should have run but 64 GB might not be enough memory. `psiclass` constructs graphs from the mapped alignments and requires quite a bit of RAM for that. 

Thank you.

**Comment by vruggieri** [comment]
Thank you for the quick response.
Which should be an acceptable memory amount to run psiclass without problem?
Does the RAM requirments depend on RNA-Seq datasets used and genome size?

**Comment by sagnikbanerjee15** [comment]
Hi @vruggieri,

The RAM requirements are mainly for the psiclass graph building step. I would recommend increasing it to 100 gb.

Thanks

**Comment by vruggieri** [comment]
Ok thanks. 
I'll try on a server with more resources.
