### ISSUE TITLE
recovery points

### ISSUE THREAD

**Issue by chklopp** [sagnikbanerjee15/Finder#6]
Due to memory issues I had to relaunch finder while it was aligneing proteins with exonerate.
Strangely it restarted a the braker step. Is their a reason for this or is it possible to add a recovery point after braker?

**Comment by sagnikbanerjee15** [comment]
Hello,

Thanks for reporting. Could you please check if the `braker.gtf` file is empty. `finder` verifies that the `braker.gtf` file is non-empty. If it is blank, then the iteration will start from the BRAKER step. You can run `finder` with the option `--checkpoint 5`

Thank you.

**Comment by chklopp** [comment]
Yes my braker gtf is empty.
lrwxrwxrwx 1  test test       109 Mar  5 22:17 FINDER_run0/braker/traingenes.gtf 
-rw-r--r-- 1  test test   5554763 Mar  5 22:19 FINDER_run0/braker/traingenes.good.gtf
-rw-r--r-- 1  test test 237986195 Mar  6 02:14 FINDER_run0/braker/augustus.hints.tmp.gtf
-rw-r--r-- 1  test test 185279812 Mar  6 02:42 FINDER_run0/braker/augustus.hints.gtf
-rw-r--r-- 1  test test         0 Mar  6 02:53 FINDER_run0/braker/braker.gtf

The pipeline ran to its end. Here is the final_GTF_files directory content 
-rw-r--r-- 1  test test        0 Mar  8 15:07 braker.gtf
-rw-r--r-- 1  test test 22086269 Mar  8 15:07 combined_redundant_transcripts_removed.gtf
-rw-r--r-- 1  test test 22242046 Mar  8 15:07 combined_split_transcripts_with_bad_SJ_redundancy_removed.gtf
-rw-r--r-- 1  test test 31848032 Mar  8 15:07 combined_with_CDS.gtf
-rw-r--r-- 1  test test   109819 Mar  8 15:07 combined_with_CDS_low_conf.gtf
-rw-r--r-- 1  test test 31738213 Mar  8 15:07 combined_with_CDS_high_conf.gtf
-rw-r--r-- 1  test test 31848032 Mar  8 15:07 combined_with_CDS_high_and_low_confidence_merged.gtf
-rw-r--r-- 1  test test 31738213 Mar  8 15:07 combined_with_CDS_BRAKER_appended_high_conf.gtf
-rw-r--r-- 1  test test 31738213 Mar  8 15:07 FINDER_BRAKER_PROT.gtf
-rw-r--r-- 1  test test  1183116 Mar  8 15:07 transcript_to_condition

**Comment by sagnikbanerjee15** [comment]
Thank you for sending me the contents of `final_GTF_files`.

There must be an issue with BRAKER. Could you please send me the error file? You will find it in braker.error under the output directory. 

Thank you.

**Comment by chklopp** [comment]
I found an error in braker/gushr.log 
Error in file /usr/local/bioinfo/src/Finder/finder-a3746f0/dep/GUSHR/gushr.py at line 281: Return code of subprocess was 1['/usr/local/bioinfo/src/Miniconda/Miniconda3-4.7.10/envs/finder-a3746f0_env/bin/java', '-jar', '/usr/local/bioinfo/src/Finder/finder-a3746f0/dep/GUSHR/GeMoMa-1.6.2.jar', 'CLI', 'ERE', 'm=./gushr-UZPXCRBSPWHN/rnaseq_merged.bam', 'u=true', 'c=true', 'outdir=./gushr-UZPXCRBSPWHN/']

**Comment by chklopp** [comment]
I tried to run the java command and it looks like an XML (finder-a3746f0/dep/GUSHR/GeMoMa.ini.xml) file is missing

/usr/local/bioinfo/src/Miniconda/Miniconda3-4.7.10/envs/finder-a3746f0_env/bin/java -jar /usr/local/bioinfo/src/Finder/finder-a3746f0/dep/GUSHR/GeMoMa-1.6.2.jar CLI ERE m=./gushr-UZPXCRBSPWHN/rnaseq_merged.bam u=true c=true outdir=./gushr-UZPXCRBSPWHN/
jar time stamp: Mon Mar 01 09:15:13 CET 2021

Searching for the new GeMoMa updates ...
You are using GeMoMa 1.6.2, but the latest version is 1.7.1.
You can download the latest version from http://www.jstacs.de/index.php/GeMoMa

Exception in thread "main" java.io.FileNotFoundException: /usr/local/bioinfo/src/Finder/finder-a3746f0/dep/GUSHR/GeMoMa.ini.xml (Permission non accordée)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at de.jstacs.io.FileManager.writeFile(FileManager.java:268)
	at projects.gemoma.GeMoMa.main(GeMoMa.java:329)

**Comment by sagnikbanerjee15** [comment]
Thank you for looking into it. GUSHR is executed only when BRAKER is asked to generate UTR sequences. In any case, BRAKER performs poorly with the UTR option turned on. I made an update a few days ago where I changed the default behavior of `finder` to instruct BRAKER to skip generating UTRs. Did you run `finder` with `--addUTR` option? You might want to try without providing that option.

Thank you.

**Comment by chklopp** [comment]
I ran braker with --addUTR .
If I remove the option and rerun will it rerun the complete braker step?

**Comment by sagnikbanerjee15** [comment]
If the `braker.gtf` file is empty then yes `finder` will rerun the BRAKER step.

Thank you.

**Comment by chklopp** [comment]
Are the other result files found in  final_GTF_files OK or should I rerun?

**Comment by sagnikbanerjee15** [comment]
The other files are OK. You can leave those as is. 

Thank you.
